name: Trigger auto deployment for container-app-2mr4jvnedzke6

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/container-app-2mr4jvnedzke6-AutoDeployTrigger-fb8eaad6-1f19-46ca-971e-a51da8b7fe9c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP2MR4JVNEDZKE6_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP2MR4JVNEDZKE6_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP2MR4JVNEDZKE6_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistry2mr4jvnedzke6.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPP2MR4JVNEDZKE6_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP2MR4JVNEDZKE6_REGISTRY_PASSWORD }}
          containerAppName: container-app-2mr4jvnedzke6
          resourceGroup: githubactiontestappnodeb937
          imageToBuild: containerregistry2mr4jvnedzke6.azurecr.io/container-app-2mr4jvnedzke6:${{ github.sha }}
          


