# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - yo-webapp-lin-container

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://yoonaohacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3a47a63857734eb4886de78a4be0de6c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a39dcf3701c34f27b4abde7ab6c48e1c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: yoonaohacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3a47a63857734eb4886de78a4be0de6c }}/hello-world:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'yo-webapp-lin-container'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1481aaa817dc44298933633371b091d7 }}
        images: 'yoonaohacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3a47a63857734eb4886de78a4be0de6c }}/hello-world:${{ github.sha }}'